Issue #1602 - Add get_label_instances to Analysis
snorkel-team/snorkel pull request #1608
Opened 2020-08-26 12:06 UTC by DavidKoleczek

## Description of proposed changes
Implements changes as discussed in #1602. Added a method to `analysis/error_analysis` that wraps `get_label_buckets` functionality. Given a _bucket_, a NumPy array _x_ of your data, and corresponding `y` label(s), it will return to you `x` with only the instances corresponding to that bucket. 

Let me know if there are any issues, questions, or suggestions. Thanks! 

## Related issue(s)

Issue #1602 

## Checklist

Need help on these? Just ask!

* [x] I have read the **CONTRIBUTING** document.
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] I have run `tox -e complex` and/or `tox -e spark` if appropriate.
* [x] All new and existing tests passed.

2020-09-04 21:42 UTC, bhancock8 requested changes
Great PR! We really appreciate the thorough docstring and tests. Just a few documentation bits to clarify, then we should be good to go!

2020-09-04 21:42 UTC, bhancock8 commented on snorkel/analysis/error_analysis.py
> +    """Return instances in x that were labeled according to bucket.
Nit: Since 'bucket' isn't a standard term, how about "Return instances in x with the specified combination of labels"

2020-09-04 21:42 UTC, bhancock8 commented on snorkel/analysis/error_analysis.py
> +    """Return instances in x that were labeled according to bucket.
Same for the docstring for the return statement

2020-09-04 21:42 UTC, bhancock8 commented on snorkel/analysis/error_analysis.py
> +    ``x`` is a NumPy array of data instances used to generate labels, `Y_gold`` is a set of
"used to generate labels" may be a misnomer. How about "data instances that the labels correspond to"?

2020-09-04 21:42 UTC, bhancock8 commented on snorkel/analysis/error_analysis.py
> +    The returned NumPy array of data instances corresponds to the data instances in x where
As you know from your tests, the method isn't limited to just two label vectors. Let's make this comment more general or make it clear that it's talking specifically about the example above, perhaps by moving up by the other Example text, above the code.

2020-09-04 21:42 UTC, bhancock8 commented on snorkel/analysis/error_analysis.py
> +        # Note: the check for all y having the same number of elements occurs in get_label_buckets
Great comment!

2020-09-05 21:19 UTC, DavidKoleczek commented
Thanks for the great comments @bhancock8 ! I made the requested changes, let me know if there is anything else.

2020-09-05 21:24 UTC, bhancock8 approved these changes
Looks good to me! Thanks for the contribution!

2020-09-05 21:24 UTC, merged